"""Explicit Phase 5 operator DDL used by the approved fresh baseline."""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


def create_operator_schema() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operator_runs",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("trigger", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("analyzer_version", sa.String(length=64), nullable=False),
        sa.Column(
            "provenance",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "summary",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_actor_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'failed', 'stopped')",
            name=op.f("ck_operator_runs_operator_runs_status"),
        ),
        sa.CheckConstraint(
            "trigger IN ('manual', 'scheduled', 'significant_event')",
            name=op.f("ck_operator_runs_operator_runs_trigger"),
        ),
        sa.CheckConstraint(
            "length(idempotency_key) > 0",
            name=op.f("ck_operator_runs_operator_runs_idempotency_key"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_actor_id"],
            ["users.id"],
            name=op.f("fk_operator_runs_created_by_actor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "product_id"],
            ["products.workspace_id", "products.id"],
            name="fk_operator_runs_product_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_operator_runs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operator_runs")),
        sa.UniqueConstraint("workspace_id", "id", name="uq_operator_runs_workspace_id_id"),
        sa.UniqueConstraint(
            "workspace_id", "idempotency_key", name="uq_operator_runs_workspace_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_operator_runs_product_id"), "operator_runs", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_operator_runs_workspace_id"), "operator_runs", ["workspace_id"], unique=False
    )
    op.create_table(
        "marketing_plans",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("operator_run_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column(
            "provenance",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("created_by_actor_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'completed', 'cancelled')",
            name=op.f("ck_marketing_plans_marketing_plans_status"),
        ),
        sa.CheckConstraint(
            "length(idempotency_key) > 0",
            name=op.f("ck_marketing_plans_marketing_plans_idempotency_key"),
        ),
        sa.CheckConstraint(
            "period_end > period_start", name=op.f("ck_marketing_plans_marketing_plans_period")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_actor_id"],
            ["users.id"],
            name=op.f("fk_marketing_plans_created_by_actor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "operator_run_id"],
            ["operator_runs.workspace_id", "operator_runs.id"],
            name="fk_marketing_plans_operator_run_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_marketing_plans_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_marketing_plans")),
        sa.UniqueConstraint("workspace_id", "id", name="uq_marketing_plans_workspace_id_id"),
        sa.UniqueConstraint(
            "workspace_id", "idempotency_key", name="uq_marketing_plans_workspace_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_marketing_plans_operator_run_id"),
        "marketing_plans",
        ["operator_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_marketing_plans_workspace_id"), "marketing_plans", ["workspace_id"], unique=False
    )
    op.create_table(
        "opportunities",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("operator_run_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column(
            "evidence_ids",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("interpretation", sa.Text(), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column("confidence", sa.String(length=10), nullable=False),
        sa.Column(
            "missing_information",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("approval_level", sa.String(length=16), nullable=False),
        sa.Column("measurement_window", sa.String(length=64), nullable=False),
        sa.Column(
            "stop_conditions",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("impact_score", sa.Integer(), nullable=False),
        sa.Column("effort_score", sa.Integer(), nullable=False),
        sa.Column("urgency_score", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("cooldown_dedup_key", sa.String(length=255), nullable=False),
        sa.Column("cooldown_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "provenance",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("created_by_actor_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "approval_level IN ('safe', 'review', 'required')",
            name=op.f("ck_opportunities_opportunities_approval_level"),
        ),
        sa.CheckConstraint(
            "confidence IN ('low', 'medium', 'high')",
            name=op.f("ck_opportunities_opportunities_confidence"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'planned', 'completed', 'dismissed')",
            name=op.f("ck_opportunities_opportunities_status"),
        ),
        sa.CheckConstraint(
            "effort_score BETWEEN 0 AND 100",
            name=op.f("ck_opportunities_opportunities_effort_score"),
        ),
        sa.CheckConstraint(
            "impact_score BETWEEN 0 AND 100",
            name=op.f("ck_opportunities_opportunities_impact_score"),
        ),
        sa.CheckConstraint(
            "length(cooldown_dedup_key) > 0",
            name=op.f("ck_opportunities_opportunities_cooldown_key"),
        ),
        sa.CheckConstraint(
            "urgency_score BETWEEN 0 AND 100",
            name=op.f("ck_opportunities_opportunities_urgency_score"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_actor_id"],
            ["users.id"],
            name=op.f("fk_opportunities_created_by_actor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "operator_run_id"],
            ["operator_runs.workspace_id", "operator_runs.id"],
            name="fk_opportunities_operator_run_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "product_id"],
            ["products.workspace_id", "products.id"],
            name="fk_opportunities_product_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_opportunities_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunities")),
        sa.UniqueConstraint("workspace_id", "id", name="uq_opportunities_workspace_id_id"),
    )
    op.create_index(
        op.f("ix_opportunities_operator_run_id"), "opportunities", ["operator_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_opportunities_product_id"), "opportunities", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_opportunities_workspace_id"), "opportunities", ["workspace_id"], unique=False
    )
    op.create_table(
        "plan_actions",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("opportunity_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "evidence_ids",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("confidence", sa.String(length=10), nullable=False),
        sa.Column(
            "missing_information",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("approval_level", sa.String(length=16), nullable=False),
        sa.Column("approval_status", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("cooldown_dedup_key", sa.String(length=255), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column(
            "provenance",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "approval_level IN ('safe', 'review', 'required')",
            name=op.f("ck_plan_actions_plan_actions_approval_level"),
        ),
        sa.CheckConstraint(
            "approval_status IN ('not_required', 'pending', 'approved', 'rejected')",
            name=op.f("ck_plan_actions_plan_actions_approval_status"),
        ),
        sa.CheckConstraint(
            "confidence IN ('low', 'medium', 'high')",
            name=op.f("ck_plan_actions_plan_actions_confidence"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'ready', 'executing', 'completed', 'failed', 'cancelled')",
            name=op.f("ck_plan_actions_plan_actions_status"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "opportunity_id"],
            ["opportunities.workspace_id", "opportunities.id"],
            name="fk_plan_actions_opportunity_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "plan_id"],
            ["marketing_plans.workspace_id", "marketing_plans.id"],
            name="fk_plan_actions_plan_id_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_plan_actions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_actions")),
        sa.UniqueConstraint("workspace_id", "id", name="uq_plan_actions_workspace_id_id"),
        sa.UniqueConstraint(
            "workspace_id", "idempotency_key", name="uq_plan_actions_workspace_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_plan_actions_opportunity_id"), "plan_actions", ["opportunity_id"], unique=False
    )
    op.create_index(op.f("ix_plan_actions_plan_id"), "plan_actions", ["plan_id"], unique=False)
    op.create_index(
        op.f("ix_plan_actions_workspace_id"), "plan_actions", ["workspace_id"], unique=False
    )
    op.create_table(
        "approval_requests",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("action_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("requested_by_actor_id", sa.Uuid(), nullable=False),
        sa.Column("decided_by_actor_id", sa.Uuid(), nullable=True),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "provenance",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected')",
            name=op.f("ck_approval_requests_approval_requests_status"),
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_actor_id"],
            ["users.id"],
            name=op.f("fk_approval_requests_decided_by_actor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_actor_id"],
            ["users.id"],
            name=op.f("fk_approval_requests_requested_by_actor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "action_id"],
            ["plan_actions.workspace_id", "plan_actions.id"],
            name="fk_approval_requests_action_id_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_approval_requests_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_requests")),
        sa.UniqueConstraint(
            "workspace_id", "action_id", name="uq_approval_requests_workspace_action"
        ),
        sa.UniqueConstraint("workspace_id", "id", name="uq_approval_requests_workspace_id_id"),
    )
    op.create_index(
        op.f("ix_approval_requests_action_id"), "approval_requests", ["action_id"], unique=False
    )
    op.create_index(
        op.f("ix_approval_requests_workspace_id"),
        "approval_requests",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "measurement_windows",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("action_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "metric_contract",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "baseline",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "result",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column(
            "provenance",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('scheduled', 'measuring', 'completed', 'cancelled')",
            name=op.f("ck_measurement_windows_measurement_windows_status"),
        ),
        sa.CheckConstraint(
            "ends_at > starts_at", name=op.f("ck_measurement_windows_measurement_windows_period")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "action_id"],
            ["plan_actions.workspace_id", "plan_actions.id"],
            name="fk_measurement_windows_action_id_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_measurement_windows_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_measurement_windows")),
        sa.UniqueConstraint("workspace_id", "id", name="uq_measurement_windows_workspace_id_id"),
        sa.UniqueConstraint(
            "workspace_id", "idempotency_key", name="uq_measurement_windows_workspace_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_measurement_windows_action_id"), "measurement_windows", ["action_id"], unique=False
    )
    op.create_index(
        op.f("ix_measurement_windows_workspace_id"),
        "measurement_windows",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "execution_runs",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("action_id", sa.Uuid(), nullable=False),
        sa.Column("approval_request_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column(
            "output",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "provenance",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_actor_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'failed', 'blocked')",
            name=op.f("ck_execution_runs_execution_runs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_actor_id"],
            ["users.id"],
            name=op.f("fk_execution_runs_created_by_actor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "action_id"],
            ["plan_actions.workspace_id", "plan_actions.id"],
            name="fk_execution_runs_action_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "approval_request_id"],
            ["approval_requests.workspace_id", "approval_requests.id"],
            name="fk_execution_runs_approval_request_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_execution_runs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution_runs")),
        sa.UniqueConstraint("workspace_id", "id", name="uq_execution_runs_workspace_id_id"),
        sa.UniqueConstraint(
            "workspace_id", "idempotency_key", name="uq_execution_runs_workspace_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_execution_runs_action_id"), "execution_runs", ["action_id"], unique=False
    )
    op.create_index(
        op.f("ix_execution_runs_workspace_id"), "execution_runs", ["workspace_id"], unique=False
    )
    op.create_table(
        "verification_runs",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("execution_run_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("method", sa.String(length=64), nullable=False),
        sa.Column(
            "result",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column(
            "provenance",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'passed', 'failed')",
            name=op.f("ck_verification_runs_verification_runs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "execution_run_id"],
            ["execution_runs.workspace_id", "execution_runs.id"],
            name="fk_verification_runs_execution_run_id_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_verification_runs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_runs")),
        sa.UniqueConstraint("workspace_id", "id", name="uq_verification_runs_workspace_id_id"),
        sa.UniqueConstraint(
            "workspace_id", "idempotency_key", name="uq_verification_runs_workspace_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_verification_runs_execution_run_id"),
        "verification_runs",
        ["execution_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_runs_workspace_id"),
        "verification_runs",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def drop_operator_schema() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_verification_runs_workspace_id"), table_name="verification_runs")
    op.drop_index(op.f("ix_verification_runs_execution_run_id"), table_name="verification_runs")
    op.drop_table("verification_runs")
    op.drop_index(op.f("ix_execution_runs_workspace_id"), table_name="execution_runs")
    op.drop_index(op.f("ix_execution_runs_action_id"), table_name="execution_runs")
    op.drop_table("execution_runs")
    op.drop_index(op.f("ix_measurement_windows_workspace_id"), table_name="measurement_windows")
    op.drop_index(op.f("ix_measurement_windows_action_id"), table_name="measurement_windows")
    op.drop_table("measurement_windows")
    op.drop_index(op.f("ix_approval_requests_workspace_id"), table_name="approval_requests")
    op.drop_index(op.f("ix_approval_requests_action_id"), table_name="approval_requests")
    op.drop_table("approval_requests")
    op.drop_index(op.f("ix_plan_actions_workspace_id"), table_name="plan_actions")
    op.drop_index(op.f("ix_plan_actions_plan_id"), table_name="plan_actions")
    op.drop_index(op.f("ix_plan_actions_opportunity_id"), table_name="plan_actions")
    op.drop_table("plan_actions")
    op.drop_index(op.f("ix_opportunities_workspace_id"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_product_id"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_operator_run_id"), table_name="opportunities")
    op.drop_table("opportunities")
    op.drop_index(op.f("ix_marketing_plans_workspace_id"), table_name="marketing_plans")
    op.drop_index(op.f("ix_marketing_plans_operator_run_id"), table_name="marketing_plans")
    op.drop_table("marketing_plans")
    op.drop_index(op.f("ix_operator_runs_workspace_id"), table_name="operator_runs")
    op.drop_index(op.f("ix_operator_runs_product_id"), table_name="operator_runs")
    op.drop_table("operator_runs")
    # ### end Alembic commands ###
