"""initial product schema

Revision ID: 0001_initial_product_schema
Revises:
Create Date: 2026-07-19 17:27:00.369554
"""

# Generated DDL keeps complete constraint expressions readable.
# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.modules.operator.migration import create_operator_schema, drop_operator_schema

revision: str = "0001_initial_product_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_transactions",
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("code_verifier_ciphertext", sa.String(length=512), nullable=False),
        sa.Column("return_path", sa.String(length=2048), nullable=False),
        sa.Column("redirect_uri", sa.String(length=2048), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_transactions")),
    )
    op.create_index(
        op.f("ix_oauth_transactions_created_by"), "oauth_transactions", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_oauth_transactions_deleted_at"), "oauth_transactions", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_oauth_transactions_expires_at"), "oauth_transactions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_oauth_transactions_provider"), "oauth_transactions", ["provider"], unique=False
    )
    op.create_index(
        op.f("ix_oauth_transactions_state_hash"), "oauth_transactions", ["state_hash"], unique=True
    )
    op.create_index(
        op.f("ix_oauth_transactions_updated_by"), "oauth_transactions", ["updated_by"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("github_id", sa.String(length=255), nullable=True),
        sa.Column("github_username", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_verified", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("github_installation_id", sa.Integer(), nullable=True),
        sa.Column("onboarding_completed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("tone_preference", sa.String(length=20), server_default="casual", nullable=False),
        sa.Column(
            "email_notifications_enabled", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column(
            "achievement_digest_enabled", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "achievement_digest_frequency",
            sa.String(length=20),
            server_default="weekly",
            nullable=False,
        ),
        sa.Column(
            "achievement_digest_prompt_dismissed",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "achievement_digest_onboarding_seen",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "last_notified_pending_draft_created_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("last_dashboard_viewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "voice_profile",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text(
                '\'{"tone_modes": ["concise", "direct"], "style_samples": [], "phrases_to_avoid": [], "audience_preference": ""}\''
            ),
            nullable=False,
        ),
        sa.Column(
            "safety_settings",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text(
                '\'{"blocked_terms": [], "ignored_paths": [], "blocked_topics": [], "private_repo_mode": "normal", "max_drafts_per_week": 14, "preferred_event_types": ["push", "release", "pull_request_merged"]}\''
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "achievement_digest_frequency IN ('weekly', 'monthly')",
            name=op.f("ck_users_users_achievement_digest_frequency"),
        ),
        sa.CheckConstraint(
            "tone_preference IN ('casual', 'technical', 'hype')",
            name=op.f("ck_users_users_tone_preference"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("github_id", name=op.f("uq_users_github_id")),
    )
    op.create_index(op.f("ix_users_created_by"), "users", ["created_by"], unique=False)
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_updated_by"), "users", ["updated_by"], unique=False)
    op.create_table(
        "workspaces",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
    )
    op.create_index(op.f("ix_workspaces_created_by"), "workspaces", ["created_by"], unique=False)
    op.create_index(op.f("ix_workspaces_deleted_at"), "workspaces", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_workspaces_updated_by"), "workspaces", ["updated_by"], unique=False)
    op.create_table(
        "auth_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("device_name", sa.String(length=120), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("replaced_by_id", sa.Uuid(), nullable=True),
        sa.Column("compromised_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_workspace_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["current_workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_auth_sessions_current_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["auth_sessions.id"],
            name=op.f("fk_auth_sessions_replaced_by_id_auth_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_auth_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
    )
    op.create_index(
        op.f("ix_auth_sessions_created_by"), "auth_sessions", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_auth_sessions_current_workspace_id"),
        "auth_sessions",
        ["current_workspace_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_auth_sessions_deleted_at"), "auth_sessions", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_auth_sessions_expires_at"), "auth_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_auth_sessions_family_id"), "auth_sessions", ["family_id"], unique=False
    )
    op.create_index(
        op.f("ix_auth_sessions_refresh_token_hash"),
        "auth_sessions",
        ["refresh_token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_auth_sessions_updated_by"), "auth_sessions", ["updated_by"], unique=False
    )
    op.create_index(op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False)
    op.create_table(
        "github_raw_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("github_delivery_id", sa.Text(), nullable=False),
        sa.Column("event_name", sa.Text(), nullable=False),
        sa.Column("repo_full_name", sa.Text(), nullable=False),
        sa.Column("payload_ciphertext", sa.Text(), nullable=False),
        sa.Column("payload_key_version", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_github_raw_events")),
        sa.UniqueConstraint("github_delivery_id", name="uq_github_raw_events_delivery"),
        comment="Restricted provider ingress; never expose through product APIs or logs.",
    )
    op.create_table(
        "integration_connections",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("external_account_id", sa.String(length=255), nullable=False),
        sa.Column("external_username", sa.String(length=255), nullable=True),
        sa.Column("credentials_ciphertext", sa.Text(), nullable=False),
        sa.Column("credential_key_version", sa.String(length=64), nullable=False),
        sa.Column(
            "scopes",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("status", sa.String(length=32), server_default="active", nullable=False),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('active', 'expired', 'revoked', 'error')",
            name=op.f("ck_integration_connections_integration_connections_status"),
        ),
        sa.CheckConstraint(
            "length(idempotency_key) > 0",
            name=op.f(
                "ck_integration_connections_integration_connections_idempotency_key_nonempty"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_integration_connections_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_connections")),
        sa.UniqueConstraint("idempotency_key", name="uq_integration_connections_idempotency_key"),
        sa.UniqueConstraint(
            "workspace_id",
            "provider",
            "external_account_id",
            name="uq_integration_connections_workspace_provider_account",
        ),
    )
    op.create_index(
        op.f("ix_integration_connections_created_by"),
        "integration_connections",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_connections_deleted_at"),
        "integration_connections",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_connections_provider"),
        "integration_connections",
        ["provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_connections_updated_by"),
        "integration_connections",
        ["updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_connections_workspace_id"),
        "integration_connections",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "oauth_identities",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("provider_subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.String(length=2048), nullable=True),
        sa.Column("email_verified", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_oauth_identities_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_identities")),
        sa.UniqueConstraint(
            "provider", "provider_subject", name="uq_oauth_identity_provider_subject"
        ),
    )
    op.create_index(
        op.f("ix_oauth_identities_created_by"), "oauth_identities", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_oauth_identities_deleted_at"), "oauth_identities", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_oauth_identities_provider"), "oauth_identities", ["provider"], unique=False
    )
    op.create_index(
        op.f("ix_oauth_identities_updated_by"), "oauth_identities", ["updated_by"], unique=False
    )
    op.create_index(
        op.f("ix_oauth_identities_user_id"), "oauth_identities", ["user_id"], unique=False
    )
    op.create_table(
        "products",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("target_audience", sa.Text(), nullable=True),
        sa.Column("messaging_angle", sa.Text(), nullable=True),
        sa.Column("tone_override", sa.String(length=20), nullable=True),
        sa.Column(
            "blocked_terms",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "blocked_topics",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "safe_public_boundaries",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("website_url", sa.Text(), nullable=True),
        sa.Column("content_mode", sa.String(length=20), server_default="builder", nullable=False),
        sa.Column("primary_customer_pain", sa.Text(), nullable=True),
        sa.Column("desired_outcome", sa.Text(), nullable=True),
        sa.Column("positioning_statement", sa.Text(), nullable=True),
        sa.Column(
            "proof_points",
            postgresql.ARRAY(sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "customer_use_cases",
            postgresql.ARRAY(sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("content_goal", sa.String(length=20), server_default="", nullable=False),
        sa.Column("cta_preference", sa.Text(), nullable=True),
        sa.Column("founder_story_angle", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "content_goal IN ('', 'awareness', 'waitlist', 'trial', 'retention', 'launch', 'feedback')",
            name=op.f("ck_products_products_content_goal"),
        ),
        sa.CheckConstraint(
            "content_mode IN ('builder', 'product')", name=op.f("ck_products_products_content_mode")
        ),
        sa.CheckConstraint(
            "tone_override IS NULL OR tone_override IN ('casual', 'technical', 'hype')",
            name=op.f("ck_products_products_tone_override"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_products_user_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_products_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("workspace_id", "id", name="uq_products_workspace_id_id"),
    )
    op.create_index(op.f("ix_products_user_id"), "products", ["user_id"], unique=False)
    op.create_index(op.f("ix_products_workspace_id"), "products", ["workspace_id"], unique=False)
    op.create_table(
        "evidence_items",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_type", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("public_safe_summary", sa.Text(), nullable=True),
        sa.Column("what_happened", sa.Text(), nullable=True),
        sa.Column("why_it_matters", sa.Text(), nullable=True),
        sa.Column("source_type", sa.Text(), nullable=False),
        sa.Column("source_reference", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confidence", sa.Text(), server_default="medium", nullable=False),
        sa.Column("classification", sa.Text(), server_default="public", nullable=False),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_actor_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "classification IN ('public', 'restricted', 'confidential', 'blocked')",
            name=op.f("ck_evidence_items_evidence_items_classification"),
        ),
        sa.CheckConstraint(
            "confidence IN ('low', 'medium', 'high')",
            name=op.f("ck_evidence_items_evidence_items_confidence"),
        ),
        sa.CheckConstraint(
            "evidence_type IN ('manual_note', 'url', 'customer_quote')",
            name=op.f("ck_evidence_items_evidence_items_evidence_type"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'stale', 'contradicted')",
            name=op.f("ck_evidence_items_evidence_items_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_actor_id"],
            ["users.id"],
            name=op.f("fk_evidence_items_created_by_actor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "product_id"],
            ["products.workspace_id", "products.id"],
            name="fk_evidence_items_product_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_evidence_items_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_items")),
        sa.UniqueConstraint("workspace_id", "id", name="uq_evidence_items_workspace_id_id"),
    )
    op.create_index(
        op.f("ix_evidence_items_product_id"), "evidence_items", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_items_workspace_id"), "evidence_items", ["workspace_id"], unique=False
    )
    op.create_table(
        "claims",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="draft", nullable=False),
        sa.Column("created_by_actor_id", sa.Uuid(), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft', 'approved', 'rejected', 'stale', 'contradicted')",
            name=op.f("ck_claims_claims_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_actor_id"],
            ["users.id"],
            name=op.f("fk_claims_created_by_actor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "product_id"],
            ["products.workspace_id", "products.id"],
            name="fk_claims_product_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_claims_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claims")),
        sa.UniqueConstraint("workspace_id", "id", name="uq_claims_workspace_id_id"),
    )
    op.create_index(op.f("ix_claims_product_id"), "claims", ["product_id"], unique=False)
    op.create_index(op.f("ix_claims_workspace_id"), "claims", ["workspace_id"], unique=False)
    op.create_table(
        "evidence_excerpts",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_item_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("locator", sa.Text(), nullable=True),
        sa.Column("created_by_actor_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_actor_id"],
            ["users.id"],
            name=op.f("fk_evidence_excerpts_created_by_actor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "evidence_item_id"],
            ["evidence_items.workspace_id", "evidence_items.id"],
            name="fk_evidence_excerpts_evidence_item_id_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_evidence_excerpts_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_excerpts")),
        sa.UniqueConstraint("workspace_id", "id", name="uq_evidence_excerpts_workspace_id_id"),
    )
    op.create_index(
        op.f("ix_evidence_excerpts_evidence_item_id"),
        "evidence_excerpts",
        ["evidence_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_excerpts_workspace_id"),
        "evidence_excerpts",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "evidence_reviews",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_item_id", sa.Uuid(), nullable=False),
        sa.Column("decision", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("reviewer_id", sa.Uuid(), nullable=False),
        sa.Column(
            "reviewed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "decision IN ('approved', 'rejected')",
            name=op.f("ck_evidence_reviews_evidence_reviews_decision"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
            name=op.f("fk_evidence_reviews_reviewer_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "evidence_item_id"],
            ["evidence_items.workspace_id", "evidence_items.id"],
            name="fk_evidence_reviews_evidence_item_id_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_evidence_reviews_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_reviews")),
    )
    op.create_index(
        op.f("ix_evidence_reviews_evidence_item_id"),
        "evidence_reviews",
        ["evidence_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_reviews_workspace_id"),
        "evidence_reviews",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "claim_evidence_links",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_excerpt_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_actor_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_actor_id"],
            ["users.id"],
            name=op.f("fk_claim_evidence_links_created_by_actor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "claim_id"],
            ["claims.workspace_id", "claims.id"],
            name="fk_claim_evidence_links_claim_id_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "evidence_excerpt_id"],
            ["evidence_excerpts.workspace_id", "evidence_excerpts.id"],
            name="fk_claim_evidence_links_evidence_excerpt_id_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_claim_evidence_links_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claim_evidence_links")),
        sa.UniqueConstraint(
            "claim_id", "evidence_excerpt_id", name="uq_claim_evidence_links_claim_excerpt"
        ),
    )
    op.create_index(
        op.f("ix_claim_evidence_links_claim_id"),
        "claim_evidence_links",
        ["claim_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_claim_evidence_links_evidence_excerpt_id"),
        "claim_evidence_links",
        ["evidence_excerpt_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_claim_evidence_links_workspace_id"),
        "claim_evidence_links",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "repo_changelog_digests",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="Temporary legacy owner field; authorize by workspace_id.",
        ),
        sa.Column("frequency", sa.String(length=20), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "digest_json",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "repo_ids",
            sa.ARRAY(sa.UUID()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "entry_ids",
            sa.ARRAY(sa.UUID()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "frequency IN ('weekly', 'monthly')",
            name=op.f("ck_repo_changelog_digests_repo_changelog_digests_frequency"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_repo_changelog_digests_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_repo_changelog_digests_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repo_changelog_digests")),
    )
    op.create_index(
        op.f("ix_repo_changelog_digests_user_id"),
        "repo_changelog_digests",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_repo_changelog_digests_workspace_id"),
        "repo_changelog_digests",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "repos",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="Temporary legacy owner field; authorize by workspace_id.",
        ),
        sa.Column("tracked_branch", sa.Text(), nullable=True),
        sa.Column("repo_name", sa.Text(), nullable=False),
        sa.Column("repo_full_name", sa.Text(), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_tracked", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("private", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("language", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("changelog_digest_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "changelog_digest_frequency",
            sa.String(length=20),
            server_default="weekly",
            nullable=False,
        ),
        sa.CheckConstraint(
            "changelog_digest_frequency IN ('weekly', 'monthly')",
            name=op.f("ck_repos_repos_changelog_digest_frequency"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_repos_user_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_repos_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repos")),
        sa.UniqueConstraint("workspace_id", "id", name="uq_repos_workspace_id_id"),
        sa.UniqueConstraint("workspace_id", "repo_full_name", name="uq_repos_workspace_full_name"),
    )
    op.create_index(op.f("ix_repos_user_id"), "repos", ["user_id"], unique=False)
    op.create_index(op.f("ix_repos_workspace_id"), "repos", ["workspace_id"], unique=False)
    op.create_table(
        "workspace_memberships",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("owner", "admin", "editor", "reviewer", "viewer", name="workspace_role"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_workspace_memberships_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_workspace_memberships_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("workspace_id", "user_id", name=op.f("pk_workspace_memberships")),
    )
    op.create_table(
        "achievement_digests",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="Temporary legacy owner field; authorize by workspace_id.",
        ),
        sa.Column("frequency", sa.String(length=20), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column(
            "digest_json",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("quality_score", sa.Integer(), nullable=True),
        sa.Column("should_send", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("recommended_post", sa.Text(), nullable=True),
        sa.Column(
            "event_ids",
            sa.ARRAY(sa.UUID()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "draft_ids",
            sa.ARRAY(sa.UUID()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "repo_ids",
            sa.ARRAY(sa.UUID()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "frequency IN ('weekly', 'monthly')",
            name=op.f("ck_achievement_digests_achievement_digests_frequency"),
        ),
        sa.CheckConstraint(
            "quality_score IS NULL OR quality_score BETWEEN 0 AND 100",
            name=op.f("ck_achievement_digests_achievement_digests_quality_score"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_achievement_digests_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_achievement_digests_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "product_id"],
            ["products.workspace_id", "products.id"],
            name="fk_achievement_digests_product_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_achievement_digests_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_achievement_digests")),
        sa.UniqueConstraint("workspace_id", "id", name="uq_achievement_digests_workspace_id_id"),
    )
    op.create_index(
        op.f("ix_achievement_digests_user_id"), "achievement_digests", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_achievement_digests_workspace_id"),
        "achievement_digests",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "github_raw_event_consumers",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("raw_event_id", sa.UUID(), nullable=False),
        sa.Column("repo_id", sa.UUID(), nullable=False),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="Temporary legacy owner field; authorize by workspace_id.",
        ),
        sa.Column(
            "processing_state", sa.String(length=20), server_default="pending", nullable=False
        ),
        sa.Column("publish_attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("publish_error_category", sa.String(length=32), nullable=True),
        sa.Column("processing_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "processing_state IN ('pending', 'enqueued', 'processed', 'failed')",
            name=op.f("ck_github_raw_event_consumers_github_raw_event_consumers_processing_state"),
        ),
        sa.CheckConstraint(
            "publish_attempts >= 0",
            name=op.f("ck_github_raw_event_consumers_github_raw_event_consumers_publish_attempts"),
        ),
        sa.ForeignKeyConstraint(
            ["raw_event_id"],
            ["github_raw_events.id"],
            name=op.f("fk_github_raw_event_consumers_raw_event_id_github_raw_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"],
            ["repos.id"],
            name=op.f("fk_github_raw_event_consumers_repo_id_repos"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_github_raw_event_consumers_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "repo_id"],
            ["repos.workspace_id", "repos.id"],
            name="fk_github_raw_event_consumers_repo_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_github_raw_event_consumers_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_github_raw_event_consumers")),
        sa.UniqueConstraint(
            "workspace_id",
            "raw_event_id",
            name="uq_github_raw_event_consumers_workspace_raw_event",
        ),
        sa.UniqueConstraint(
            "workspace_id", "id", name="uq_github_raw_event_consumers_workspace_id_id"
        ),
    )
    op.create_index(
        op.f("ix_github_raw_event_consumers_user_id"),
        "github_raw_event_consumers",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_github_raw_event_consumers_workspace_id"),
        "github_raw_event_consumers",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "normalized_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="Temporary legacy owner field; authorize by workspace_id.",
        ),
        sa.Column("raw_event_id", sa.UUID(), nullable=False),
        sa.Column("repo_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("repo_full_name", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sha", sa.Text(), nullable=True),
        sa.Column("dedupe_key", sa.Text(), nullable=False),
        sa.Column(
            "enrichment",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("branch_name", sa.Text(), nullable=True),
        sa.Column(
            "touched_paths",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["raw_event_id"],
            ["github_raw_events.id"],
            name=op.f("fk_normalized_events_raw_event_id_github_raw_events"),
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"], ["repos.id"], name=op.f("fk_normalized_events_repo_id_repos")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_normalized_events_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "raw_event_id"],
            [
                "github_raw_event_consumers.workspace_id",
                "github_raw_event_consumers.raw_event_id",
            ],
            name="fk_normalized_events_raw_event_id_consumer",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "repo_id"],
            ["repos.workspace_id", "repos.id"],
            name="fk_normalized_events_repo_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_normalized_events_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_normalized_events")),
        sa.UniqueConstraint(
            "workspace_id", "dedupe_key", name="uq_normalized_events_workspace_dedupe"
        ),
        sa.UniqueConstraint("workspace_id", "id", name="uq_normalized_events_workspace_id_id"),
    )
    op.create_index(
        op.f("ix_normalized_events_user_id"), "normalized_events", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_normalized_events_workspace_id"),
        "normalized_events",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "product_repositories",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("repo_id", sa.UUID(), nullable=False),
        sa.Column("generated_role_description", sa.Text(), nullable=True),
        sa.Column("role_description_override", sa.Text(), nullable=True),
        sa.Column("role_description_generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("role_description_generation_version", sa.Integer(), nullable=True),
        sa.Column("repo_role", sa.String(length=20), server_default="unknown", nullable=False),
        sa.Column("is_primary_repo", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "repo_role IN ('frontend', 'backend', 'mobile', 'worker', 'infra', 'docs', 'shared_lib', 'unknown')",
            name=op.f("ck_product_repositories_product_repositories_repo_role"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_repositories_product_id_products"),
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"], ["repos.id"], name=op.f("fk_product_repositories_repo_id_repos")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "product_id"],
            ["products.workspace_id", "products.id"],
            name="fk_product_repositories_product_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "repo_id"],
            ["repos.workspace_id", "repos.id"],
            name="fk_product_repositories_repo_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_product_repositories_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_repositories")),
        sa.UniqueConstraint("repo_id", name=op.f("uq_product_repositories_repo_id")),
    )
    op.create_index(
        op.f("ix_product_repositories_workspace_id"),
        "product_repositories",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "uq_product_repositories_primary_product",
        "product_repositories",
        ["workspace_id", "product_id"],
        unique=True,
        postgresql_where=sa.text("is_primary_repo IS true"),
    )
    op.create_table(
        "achievement_digest_feedback",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="Temporary legacy owner field; authorize by workspace_id.",
        ),
        sa.Column("digest_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('useful', 'not_useful', 'copied', 'converted_to_draft', 'dismissed')",
            name=op.f("ck_achievement_digest_feedback_achievement_digest_feedback_action"),
        ),
        sa.ForeignKeyConstraint(
            ["digest_id"],
            ["achievement_digests.id"],
            name=op.f("fk_achievement_digest_feedback_digest_id_achievement_digests"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_achievement_digest_feedback_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "digest_id"],
            ["achievement_digests.workspace_id", "achievement_digests.id"],
            name="fk_achievement_digest_feedback_digest_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_achievement_digest_feedback_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_achievement_digest_feedback")),
    )
    op.create_index(
        op.f("ix_achievement_digest_feedback_user_id"),
        "achievement_digest_feedback",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_achievement_digest_feedback_workspace_id"),
        "achievement_digest_feedback",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "event_evaluations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="Temporary legacy owner field; authorize by workspace_id.",
        ),
        sa.Column("normalized_event_id", sa.UUID(), nullable=False),
        sa.Column("repo_id", sa.UUID(), nullable=False),
        sa.Column("public_worthiness_score", sa.Integer(), nullable=False),
        sa.Column("is_public_worthy", sa.Boolean(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column(
            "failed_safety_checks",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("outcome", sa.String(length=20), server_default="ignore", nullable=False),
        sa.Column(
            "dimension_scores",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("internal_summary", sa.Text(), nullable=True),
        sa.Column("public_summary", sa.Text(), nullable=True),
        sa.Column("user_benefit", sa.Text(), nullable=True),
        sa.Column("target_audience", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "outcome IN ('generate', 'hold', 'ignore', 'block')",
            name=op.f("ck_event_evaluations_event_evaluations_outcome"),
        ),
        sa.ForeignKeyConstraint(
            ["normalized_event_id"],
            ["normalized_events.id"],
            name=op.f("fk_event_evaluations_normalized_event_id_normalized_events"),
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"], ["repos.id"], name=op.f("fk_event_evaluations_repo_id_repos")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_event_evaluations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "normalized_event_id"],
            ["normalized_events.workspace_id", "normalized_events.id"],
            name="fk_event_evaluations_normalized_event_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "repo_id"],
            ["repos.workspace_id", "repos.id"],
            name="fk_event_evaluations_repo_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_event_evaluations_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_evaluations")),
        sa.UniqueConstraint(
            "normalized_event_id", name=op.f("uq_event_evaluations_normalized_event_id")
        ),
        sa.UniqueConstraint("workspace_id", "id", name="uq_event_evaluations_workspace_id_id"),
    )
    op.create_index(
        op.f("ix_event_evaluations_user_id"), "event_evaluations", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_event_evaluations_workspace_id"),
        "event_evaluations",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "generation_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="Temporary legacy owner field; authorize by workspace_id.",
        ),
        sa.Column("repo_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("normalized_event_id", sa.UUID(), nullable=True),
        sa.Column("trigger", sa.String(length=30), nullable=False),
        sa.Column("requested_angle", sa.Text(), nullable=True),
        sa.Column("context_version", sa.Integer(), nullable=False),
        sa.Column(
            "context_snapshot",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("user_prompt", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("failure_message", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "content_memory_snapshot",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text('\'{"approvedAngles": [], "recentApprovedContent": []}\''),
            nullable=False,
        ),
        sa.Column(
            "candidate_snapshot",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "provider_parameters",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('completed', 'failed')",
            name=op.f("ck_generation_runs_generation_runs_status"),
        ),
        sa.CheckConstraint(
            "trigger IN ('event_pipeline', 'angle_regeneration')",
            name=op.f("ck_generation_runs_generation_runs_trigger"),
        ),
        sa.CheckConstraint(
            "duration_ms IS NULL OR duration_ms >= 0",
            name=op.f("ck_generation_runs_generation_runs_duration"),
        ),
        sa.ForeignKeyConstraint(
            ["normalized_event_id"],
            ["normalized_events.id"],
            name=op.f("fk_generation_runs_normalized_event_id_normalized_events"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_generation_runs_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"], ["repos.id"], name=op.f("fk_generation_runs_repo_id_repos")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_generation_runs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "normalized_event_id"],
            ["normalized_events.workspace_id", "normalized_events.id"],
            name="fk_generation_runs_normalized_event_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "product_id"],
            ["products.workspace_id", "products.id"],
            name="fk_generation_runs_product_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "repo_id"],
            ["repos.workspace_id", "repos.id"],
            name="fk_generation_runs_repo_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_generation_runs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_runs")),
        sa.UniqueConstraint("workspace_id", "id", name="uq_generation_runs_workspace_id_id"),
    )
    op.create_index(
        op.f("ix_generation_runs_user_id"), "generation_runs", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_generation_runs_workspace_id"), "generation_runs", ["workspace_id"], unique=False
    )
    op.create_table(
        "repo_changelog_entries",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="Temporary legacy owner field; authorize by workspace_id.",
        ),
        sa.Column("repo_id", sa.UUID(), nullable=False),
        sa.Column("raw_event_id", sa.UUID(), nullable=False),
        sa.Column("normalized_event_id", sa.UUID(), nullable=True),
        sa.Column("sha", sa.Text(), nullable=False),
        sa.Column("commit_message", sa.Text(), nullable=False),
        sa.Column("commit_url", sa.Text(), nullable=False),
        sa.Column("author_name", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("user_benefit", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column(
            "files_changed",
            sa.ARRAY(sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("is_changelog_worthy", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "safety_flags",
            sa.ARRAY(sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 100",
            name=op.f("ck_repo_changelog_entries_repo_changelog_entries_confidence"),
        ),
        sa.ForeignKeyConstraint(
            ["normalized_event_id"],
            ["normalized_events.id"],
            name=op.f("fk_repo_changelog_entries_normalized_event_id_normalized_events"),
        ),
        sa.ForeignKeyConstraint(
            ["raw_event_id"],
            ["github_raw_events.id"],
            name=op.f("fk_repo_changelog_entries_raw_event_id_github_raw_events"),
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"], ["repos.id"], name=op.f("fk_repo_changelog_entries_repo_id_repos")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_repo_changelog_entries_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "normalized_event_id"],
            ["normalized_events.workspace_id", "normalized_events.id"],
            name="fk_repo_changelog_entries_normalized_event_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "repo_id"],
            ["repos.workspace_id", "repos.id"],
            name="fk_repo_changelog_entries_repo_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_repo_changelog_entries_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repo_changelog_entries")),
        sa.UniqueConstraint("workspace_id", "id", name="uq_repo_changelog_entries_workspace_id_id"),
        sa.UniqueConstraint(
            "workspace_id", "repo_id", "sha", name="uq_repo_changelog_entries_workspace_repo_sha"
        ),
    )
    op.create_index(
        op.f("ix_repo_changelog_entries_user_id"),
        "repo_changelog_entries",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_repo_changelog_entries_workspace_id"),
        "repo_changelog_entries",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "tweet_candidates",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="Temporary legacy owner field; authorize by workspace_id.",
        ),
        sa.Column("normalized_event_id", sa.UUID(), nullable=False),
        sa.Column("repo_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("angle", sa.String(length=40), server_default="shipping_update", nullable=False),
        sa.Column(
            "variant",
            sa.String(length=40),
            server_default="concise_shipping_update",
            nullable=False,
        ),
        sa.Column(
            "dimension_scores",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "angle IN ('user_benefit', 'problem_solved', 'shipping_update', 'technical_credibility', 'founder_build_in_public', 'milestone_or_traction', 'weekly_roundup')",
            name=op.f("ck_tweet_candidates_tweet_candidates_angle"),
        ),
        sa.CheckConstraint(
            "variant IN ('problem_solution', 'customer_value', 'founder_insight', 'soft_launch_cta', 'concise_shipping_update')",
            name=op.f("ck_tweet_candidates_tweet_candidates_variant"),
        ),
        sa.ForeignKeyConstraint(
            ["normalized_event_id"],
            ["normalized_events.id"],
            name=op.f("fk_tweet_candidates_normalized_event_id_normalized_events"),
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"], ["repos.id"], name=op.f("fk_tweet_candidates_repo_id_repos")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_tweet_candidates_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "normalized_event_id"],
            ["normalized_events.workspace_id", "normalized_events.id"],
            name="fk_tweet_candidates_normalized_event_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "repo_id"],
            ["repos.workspace_id", "repos.id"],
            name="fk_tweet_candidates_repo_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_tweet_candidates_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tweet_candidates")),
        sa.UniqueConstraint("workspace_id", "id", name="uq_tweet_candidates_workspace_id_id"),
    )
    op.create_index(
        op.f("ix_tweet_candidates_user_id"), "tweet_candidates", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_tweet_candidates_workspace_id"), "tweet_candidates", ["workspace_id"], unique=False
    )
    op.create_table(
        "drafts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="Temporary legacy owner field; authorize by workspace_id.",
        ),
        sa.Column("repo_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source_event_type", sa.Text(), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tweet_id", sa.Text(), nullable=True),
        sa.Column(
            "source_event_payload",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_edited", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("edit_distance", sa.Integer(), nullable=True),
        sa.Column("generation_run_id", sa.UUID(), nullable=True),
        sa.Column("selected_candidate_id", sa.UUID(), nullable=True),
        sa.Column("normalized_event_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("posting_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status <> 'posted' OR (posted_at IS NOT NULL AND tweet_id IS NOT NULL)",
            name=op.f("ck_drafts_drafts_post_receipt_required"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'posted')",
            name=op.f("ck_drafts_drafts_status"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('approved', 'posted') OR approved_at IS NOT NULL",
            name=op.f("ck_drafts_drafts_approval_required"),
        ),
        sa.ForeignKeyConstraint(
            ["generation_run_id"],
            ["generation_runs.id"],
            name=op.f("fk_drafts_generation_run_id_generation_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["normalized_event_id"],
            ["normalized_events.id"],
            name=op.f("fk_drafts_normalized_event_id_normalized_events"),
        ),
        sa.ForeignKeyConstraint(["repo_id"], ["repos.id"], name=op.f("fk_drafts_repo_id_repos")),
        sa.ForeignKeyConstraint(
            ["selected_candidate_id"],
            ["tweet_candidates.id"],
            name=op.f("fk_drafts_selected_candidate_id_tweet_candidates"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_drafts_user_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "generation_run_id"],
            ["generation_runs.workspace_id", "generation_runs.id"],
            name="fk_drafts_generation_run_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "normalized_event_id"],
            ["normalized_events.workspace_id", "normalized_events.id"],
            name="fk_drafts_normalized_event_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "repo_id"],
            ["repos.workspace_id", "repos.id"],
            name="fk_drafts_repo_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "selected_candidate_id"],
            ["tweet_candidates.workspace_id", "tweet_candidates.id"],
            name="fk_drafts_selected_candidate_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_drafts_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drafts")),
        sa.UniqueConstraint("workspace_id", "id", name="uq_drafts_workspace_id_id"),
    )
    op.create_index(op.f("ix_drafts_user_id"), "drafts", ["user_id"], unique=False)
    op.create_index(op.f("ix_drafts_workspace_id"), "drafts", ["workspace_id"], unique=False)
    op.create_table(
        "draft_feedback_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="Temporary legacy owner field; authorize by workspace_id.",
        ),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("repo_id", sa.UUID(), nullable=False),
        sa.Column("draft_id", sa.UUID(), nullable=False),
        sa.Column("generation_run_id", sa.UUID(), nullable=True),
        sa.Column("candidate_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=20), nullable=False),
        sa.Column("previous_candidate_id", sa.UUID(), nullable=True),
        sa.Column("content_before", sa.Text(), nullable=True),
        sa.Column("content_after", sa.Text(), nullable=True),
        sa.Column("edit_distance", sa.Integer(), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("provider_post_id", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('selected', 'edited', 'approved', 'rejected', 'posted')",
            name=op.f("ck_draft_feedback_events_draft_feedback_events_event_type"),
        ),
        sa.CheckConstraint(
            "edit_distance IS NULL OR edit_distance >= 0",
            name=op.f("ck_draft_feedback_events_draft_feedback_events_edit_distance"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["tweet_candidates.id"],
            name=op.f("fk_draft_feedback_events_candidate_id_tweet_candidates"),
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"], ["drafts.id"], name=op.f("fk_draft_feedback_events_draft_id_drafts")
        ),
        sa.ForeignKeyConstraint(
            ["generation_run_id"],
            ["generation_runs.id"],
            name=op.f("fk_draft_feedback_events_generation_run_id_generation_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["previous_candidate_id"],
            ["tweet_candidates.id"],
            name=op.f("fk_draft_feedback_events_previous_candidate_id_tweet_candidates"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_draft_feedback_events_product_id_products"),
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"], ["repos.id"], name=op.f("fk_draft_feedback_events_repo_id_repos")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_draft_feedback_events_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "candidate_id"],
            ["tweet_candidates.workspace_id", "tweet_candidates.id"],
            name="fk_draft_feedback_events_candidate_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "draft_id"],
            ["drafts.workspace_id", "drafts.id"],
            name="fk_draft_feedback_events_draft_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "generation_run_id"],
            ["generation_runs.workspace_id", "generation_runs.id"],
            name="fk_draft_feedback_events_generation_run_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "previous_candidate_id"],
            ["tweet_candidates.workspace_id", "tweet_candidates.id"],
            name="fk_draft_feedback_events_previous_candidate_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "product_id"],
            ["products.workspace_id", "products.id"],
            name="fk_draft_feedback_events_product_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "repo_id"],
            ["repos.workspace_id", "repos.id"],
            name="fk_draft_feedback_events_repo_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_draft_feedback_events_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_draft_feedback_events")),
    )
    op.create_index(
        op.f("ix_draft_feedback_events_user_id"), "draft_feedback_events", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_draft_feedback_events_workspace_id"),
        "draft_feedback_events",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "draft_status_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="Temporary legacy owner field; authorize by workspace_id.",
        ),
        sa.Column("repo_id", sa.UUID(), nullable=False),
        sa.Column("draft_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'posted')",
            name=op.f("ck_draft_status_events_draft_status_events_status"),
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"], ["drafts.id"], name=op.f("fk_draft_status_events_draft_id_drafts")
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"], ["repos.id"], name=op.f("fk_draft_status_events_repo_id_repos")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_draft_status_events_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "draft_id"],
            ["drafts.workspace_id", "drafts.id"],
            name="fk_draft_status_events_draft_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "repo_id"],
            ["repos.workspace_id", "repos.id"],
            name="fk_draft_status_events_repo_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_draft_status_events_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_draft_status_events")),
    )
    op.create_index(
        op.f("ix_draft_status_events_user_id"), "draft_status_events", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_draft_status_events_workspace_id"),
        "draft_status_events",
        ["workspace_id"],
        unique=False,
    )
    create_operator_schema()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    drop_operator_schema()
    op.drop_index(op.f("ix_draft_status_events_workspace_id"), table_name="draft_status_events")
    op.drop_index(op.f("ix_draft_status_events_user_id"), table_name="draft_status_events")
    op.drop_table("draft_status_events")
    op.drop_index(op.f("ix_draft_feedback_events_workspace_id"), table_name="draft_feedback_events")
    op.drop_index(op.f("ix_draft_feedback_events_user_id"), table_name="draft_feedback_events")
    op.drop_table("draft_feedback_events")
    op.drop_index(op.f("ix_drafts_workspace_id"), table_name="drafts")
    op.drop_index(op.f("ix_drafts_user_id"), table_name="drafts")
    op.drop_table("drafts")
    op.drop_index(op.f("ix_tweet_candidates_workspace_id"), table_name="tweet_candidates")
    op.drop_index(op.f("ix_tweet_candidates_user_id"), table_name="tweet_candidates")
    op.drop_table("tweet_candidates")
    op.drop_index(
        op.f("ix_repo_changelog_entries_workspace_id"), table_name="repo_changelog_entries"
    )
    op.drop_index(op.f("ix_repo_changelog_entries_user_id"), table_name="repo_changelog_entries")
    op.drop_table("repo_changelog_entries")
    op.drop_index(op.f("ix_generation_runs_workspace_id"), table_name="generation_runs")
    op.drop_index(op.f("ix_generation_runs_user_id"), table_name="generation_runs")
    op.drop_table("generation_runs")
    op.drop_index(op.f("ix_event_evaluations_workspace_id"), table_name="event_evaluations")
    op.drop_index(op.f("ix_event_evaluations_user_id"), table_name="event_evaluations")
    op.drop_table("event_evaluations")
    op.drop_index(
        op.f("ix_achievement_digest_feedback_workspace_id"),
        table_name="achievement_digest_feedback",
    )
    op.drop_index(
        op.f("ix_achievement_digest_feedback_user_id"), table_name="achievement_digest_feedback"
    )
    op.drop_table("achievement_digest_feedback")
    op.drop_index("uq_product_repositories_primary_product", table_name="product_repositories")
    op.drop_index(op.f("ix_product_repositories_workspace_id"), table_name="product_repositories")
    op.drop_table("product_repositories")
    op.drop_index(op.f("ix_normalized_events_workspace_id"), table_name="normalized_events")
    op.drop_index(op.f("ix_normalized_events_user_id"), table_name="normalized_events")
    op.drop_table("normalized_events")
    op.drop_index(
        op.f("ix_github_raw_event_consumers_workspace_id"),
        table_name="github_raw_event_consumers",
    )
    op.drop_index(
        op.f("ix_github_raw_event_consumers_user_id"),
        table_name="github_raw_event_consumers",
    )
    op.drop_table("github_raw_event_consumers")
    op.drop_index(op.f("ix_achievement_digests_workspace_id"), table_name="achievement_digests")
    op.drop_index(op.f("ix_achievement_digests_user_id"), table_name="achievement_digests")
    op.drop_table("achievement_digests")
    op.drop_index(op.f("ix_claim_evidence_links_workspace_id"), table_name="claim_evidence_links")
    op.drop_index(
        op.f("ix_claim_evidence_links_evidence_excerpt_id"), table_name="claim_evidence_links"
    )
    op.drop_index(op.f("ix_claim_evidence_links_claim_id"), table_name="claim_evidence_links")
    op.drop_table("claim_evidence_links")
    op.drop_index(op.f("ix_evidence_reviews_workspace_id"), table_name="evidence_reviews")
    op.drop_index(op.f("ix_evidence_reviews_evidence_item_id"), table_name="evidence_reviews")
    op.drop_table("evidence_reviews")
    op.drop_index(op.f("ix_evidence_excerpts_workspace_id"), table_name="evidence_excerpts")
    op.drop_index(op.f("ix_evidence_excerpts_evidence_item_id"), table_name="evidence_excerpts")
    op.drop_table("evidence_excerpts")
    op.drop_index(op.f("ix_claims_workspace_id"), table_name="claims")
    op.drop_index(op.f("ix_claims_product_id"), table_name="claims")
    op.drop_table("claims")
    op.drop_index(op.f("ix_evidence_items_workspace_id"), table_name="evidence_items")
    op.drop_index(op.f("ix_evidence_items_product_id"), table_name="evidence_items")
    op.drop_table("evidence_items")
    op.drop_table("workspace_memberships")
    op.drop_index(op.f("ix_repos_workspace_id"), table_name="repos")
    op.drop_index(op.f("ix_repos_user_id"), table_name="repos")
    op.drop_table("repos")
    op.drop_index(
        op.f("ix_repo_changelog_digests_workspace_id"), table_name="repo_changelog_digests"
    )
    op.drop_index(op.f("ix_repo_changelog_digests_user_id"), table_name="repo_changelog_digests")
    op.drop_table("repo_changelog_digests")
    op.drop_index(op.f("ix_products_workspace_id"), table_name="products")
    op.drop_index(op.f("ix_products_user_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_oauth_identities_user_id"), table_name="oauth_identities")
    op.drop_index(op.f("ix_oauth_identities_updated_by"), table_name="oauth_identities")
    op.drop_index(op.f("ix_oauth_identities_provider"), table_name="oauth_identities")
    op.drop_index(op.f("ix_oauth_identities_deleted_at"), table_name="oauth_identities")
    op.drop_index(op.f("ix_oauth_identities_created_by"), table_name="oauth_identities")
    op.drop_table("oauth_identities")
    op.drop_index(
        op.f("ix_integration_connections_workspace_id"), table_name="integration_connections"
    )
    op.drop_index(
        op.f("ix_integration_connections_updated_by"), table_name="integration_connections"
    )
    op.drop_index(op.f("ix_integration_connections_provider"), table_name="integration_connections")
    op.drop_index(
        op.f("ix_integration_connections_deleted_at"), table_name="integration_connections"
    )
    op.drop_index(
        op.f("ix_integration_connections_created_by"), table_name="integration_connections"
    )
    op.drop_table("integration_connections")
    op.drop_table("github_raw_events")
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_updated_by"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_refresh_token_hash"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_family_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_expires_at"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_deleted_at"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_current_workspace_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_created_by"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index(op.f("ix_workspaces_updated_by"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_deleted_at"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_created_by"), table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_index(op.f("ix_users_updated_by"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    op.drop_index(op.f("ix_users_created_by"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_oauth_transactions_updated_by"), table_name="oauth_transactions")
    op.drop_index(op.f("ix_oauth_transactions_state_hash"), table_name="oauth_transactions")
    op.drop_index(op.f("ix_oauth_transactions_provider"), table_name="oauth_transactions")
    op.drop_index(op.f("ix_oauth_transactions_expires_at"), table_name="oauth_transactions")
    op.drop_index(op.f("ix_oauth_transactions_deleted_at"), table_name="oauth_transactions")
    op.drop_index(op.f("ix_oauth_transactions_created_by"), table_name="oauth_transactions")
    op.drop_table("oauth_transactions")
    postgresql.ENUM(name="workspace_role").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
